export const TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",

  //Streaming
  CREATE_STREAMING: "CREATE_STREAMING",
  OPEN_OR_CLOSE_MODAL: "OPEN_OR_CLOSE_MODAL",
  CREATE_SESSION_STREAMING: "CREATE_SESSION_STREAMING",
};
